=head1 REST API

This document defines the REST API.  By and large, this follows the WebIOpi 
REST interface:

  https://code.google.com/p/webiopi/wiki/INSTALL?tm=6

There are a few notable differences, mostly to account for being on more 
than just the Rapsberry Pi.  For instance, the pcDuino has different 
voltage and bit resolutions for some of its ADC and PWM channels, so 
the API to access that data must specify a pin.

Specific differences are noted as "B<COMPATIBILITY NOTE>" below.

=head2 Status Codes

Just a few of the HTTP status codes you might expect to hit.

400 Bad Request (path incomplete)
403 GPIO # Not Available
403 GPIO # Disabled
404 [something] Not Found 

=head3 503 Not Implemented

The device does not support this type.  This may happen, for example, when 
you request a pwm device when there is no pwm channel to use.


=head2 GPIO

=head3 GET /devices/[name]/count

Returns the digital channel count

=head3 GET /devices/[name]/[channel]/value

=head3 GET /devices/[name]/*/value

=head3 POST /devices/[name]/[channel]/value/[digit]

=head3 GET /devices/[name]/*/integer

portRead()

(Return as CSV list?)

(B<COMPATIBILITY NOTE>: This is in the WebIOpi docs as POST)

=head3 POST /devices/[name]/*/integer/[value]

=head3 GET /devices/[name]/[channel]/function

=head3 POST /devices/[name]/[channel]/function/[func]

setFunctionString()

(B<COMPATIBILITY NOTE>: This is in the WebIOpi docs as GET)

=head3 GET /devices/[name]/*


=head2 ADC (Analog-to-Digital Converter)

=head3 GET /devices/[name]/analog/count

(B<NOTE>: Redundant listings in WebIOpi docs for analogCount and 
analogResolution)

=head3 GET /devices/[name]/analog/[channel]/maximum

analogMaximum()

(B<COMPATIBILITY NOTE>: WebIOpi does not use channel argument)

=head3 GET /devices/[name]/analog/[channel]/integer/vref

analogReference()

(B<COMPATIBILITY NOTE>: WebIOpi does not use channel argument)

=head3 GET /devices/[name]/analog/[channel]/integer

=head3 GET /devices/[name]/analog/[channel]/float

=head3 GET /devices/[name]/analog/[channel]/volt

=head3 GET /devices/[name]/analog/*/integer

analogReadAll()

(list returned as CSV?)

=head3 GET /devices/[name]/analog/*/float

(list returned as CSV?)


=head2 DAC (Digital-to-Analog Converter)

Extends ADC interface

=head3 POST /devices/[name]/analog/[channel]/integer/[value]

=head3 POST /devices/[name]/analog/[channel]/float/[value]

=head3 POST /devices/[name]/analog/[channel]/volt/[value]

=head2 PWM (Pulse Width Modulation)

=head3 GET /devices/[name]/pwm/count

=head3 GET /devices/[name]/pwm/[channel]/resolution

pwmResolution()

(B<COMPATIBILITY NOTE>: WebIOpi does not use channel argument)

=head3 GET /devices/[name]/pwm/[channel]/maximum

pwmMaximum()

(B<COMPATIBILITY NOTE>: WebIOpi does not use channel argument)

=head3 POST /devices/[name]/pwm/[channel]/integer/[value]

=head3 POST /devices/[name]/pwm/[channel]/float/[value]

=head3 POST /devices/[name]/pwm/[channel]/angle/[value]

=head3 GET /devices/[name]/pwm/[channel]/integer

=head3 GET /devices/[name]/pwm/[channel]/float

=head3 GET /devices/[name]/pwm/[channel]/angle

=head3 GET /devices/[name]/pwm/*/integer

=head3 GET /devices/[name]/pwm/*/float

=head3 GET /devices/[name]/pwm/*/angle

=head3 GET /devices/[name]/pwm/*


=head2 VideoStream

=head3 GET /devices/[name]/video/count

=head3 GET /devices/[name]/video/[channel]/resolution

=head3 POST /devices/[name]/video/[channel]/resolution/[width]/[height]

=head3 GET /devices/[name]/video/[channel]/kbps

=head3 POST /devices/[name]/video/[channel]/bps/[value]

=head3 GET /devices/[name]/video/[channel]/allowed-content-types

=head3 GET /devices/[name]/video/[channel]/stream


=head2 SPI

=head2 I2C

=head2 OneWire

=head2 Pressure

=head2 Luminosity

=head2 Distance


=end
